import Home from './../components/Home'
import Head from 'next/head'
import type { Metadata } from 'next'


export const metadata: Metadata = {
  metadataBase: new URL('http://localhost:3000'),
  title: 'VideoHub',
  description: 'Generated by create next app',
  openGraph: {
    title: 'VideoHub',
    images: ['/some-specific-page-image.jpg']

  }

}
export default function App() {

  return (
    <>
      <main className="flex min-h-screen flex-row">
        <Home></Home>
      </main>
    </>
  )
}